name: Notebook CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert nbclient papermill
      - name: Run unit tests
        run: |
          if [ -d tests ]; then pytest -q || true; fi
      - name: Execute model comparison notebook
        run: |
          mkdir -p executed_notebooks
          jupyter nbconvert --to notebook --execute notebooks/model_comparison.ipynb --ExecutePreprocessor.timeout=600 --output executed_notebooks/model_comparison_executed.ipynb
      - name: Upload executed notebook
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebooks
          path: executed_notebooks
